import { Tournament } from "@/types";

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: "tourn-1",
    name: "Inter-Department Football Champions Trophy 2026",
    slug: "inter-dept-football-2026",
    sport: "Football",
    season: "Spring 2026",
    status: "Ongoing",
    startDate: "2026-03-01",
    endDate: "2026-03-30",
    totalTeams: 12,
    prizePool: "\$1,500",
    description: "The official university inter-department football tournament featuring 12 top departmental squads.",
    teams: [
      {
        id: "team-cse",
        name: "CSE Strikers",
        shortName: "CSE",
        captainName: "Alex Vance",
        department: "Computer Science",
        played: 5,
        won: 4,
        drawn: 1,
        lost: 0,
        goalsFor: 14,
        goalsAgainst: 3,
        points: 13,
      },
      {
        id: "team-eee",
        name: "EEE Dynamos",
        shortName: "EEE",
        captainName: "Michael Ray",
        department: "Electrical Engineering",
        played: 5,
        won: 3,
        drawn: 1,
        lost: 1,
        goalsFor: 10,
        goalsAgainst: 6,
        points: 10,
      },
      {
        id: "team-me",
        name: "Mechanical Titans",
        shortName: "MECH",
        captainName: "David Miller",
        department: "Mechanical Engineering",
        played: 5,
        won: 2,
        drawn: 2,
        lost: 1,
        goalsFor: 8,
        goalsAgainst: 5,
        points: 8,
      },
      {
        id: "team-bba",
        name: "BBA Warriors",
        shortName: "BBA",
        captainName: "Sarah Jenkins",
        department: "Business Administration",
        played: 5,
        won: 1,
        drawn: 1,
        lost: 3,
        goalsFor: 5,
        goalsAgainst: 11,
        points: 4,
      },
    ],
  },
  {
    id: "tourn-2",
    name: "Campus T20 Cricket Super League",
    slug: "campus-t20-cricket-2026",
    sport: "Cricket",
    season: "Spring 2026",
    status: "Upcoming",
    startDate: "2026-04-10",
    endDate: "2026-04-28",
    totalTeams: 8,
    prizePool: "\$2,000",
    description: "High-octane T20 cricket league with 8 university teams competing for glory.",
    teams: [],
  },
];

export const tournamentService = {
  getTournaments: async (): Promise<Tournament[]> => MOCK_TOURNAMENTS,
  getTournamentById: async (id: string): Promise<Tournament | undefined> =>
    MOCK_TOURNAMENTS.find((t) => t.id === id || t.slug === id),
};
