import { Tournament, Team } from "@/types";

export const MOCK_TEAMS: Team[] = [
  {
    id: "team-cse",
    name: "CSE Strikers",
    shortName: "CSE",
    logoUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120",
    captainName: "Alex Vance",
    department: "Computer Science & Engineering",
    played: 6,
    won: 5,
    drawn: 1,
    lost: 0,
    goalsFor: 16,
    goalsAgainst: 4,
    points: 16,
  },
  {
    id: "team-eee",
    name: "EEE Dynamos",
    shortName: "EEE",
    logoUrl: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=120",
    captainName: "Michael Ray",
    department: "Electrical & Electronic Engineering",
    played: 6,
    won: 4,
    drawn: 1,
    lost: 1,
    goalsFor: 12,
    goalsAgainst: 7,
    points: 13,
  },
  {
    id: "team-me",
    name: "Mechanical Titans",
    shortName: "MECH",
    logoUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=120",
    captainName: "David Miller",
    department: "Mechanical Engineering",
    played: 6,
    won: 3,
    drawn: 2,
    lost: 1,
    goalsFor: 10,
    goalsAgainst: 6,
    points: 11,
  },
  {
    id: "team-bba",
    name: "BBA Warriors",
    shortName: "BBA",
    logoUrl: "https://images.unsplash.com/photo-1517649763962-0c623266010b?w=120",
    captainName: "Sarah Jenkins",
    department: "Business Administration",
    played: 6,
    won: 2,
    drawn: 1,
    lost: 3,
    goalsFor: 8,
    goalsAgainst: 12,
    points: 7,
  },
  {
    id: "team-ce",
    name: "Civil Knights",
    shortName: "CE",
    logoUrl: "https://images.unsplash.com/photo-1543351611-c8239486074e?w=120",
    captainName: "Robert Ford",
    department: "Civil Engineering",
    played: 6,
    won: 1,
    drawn: 1,
    lost: 4,
    goalsFor: 5,
    goalsAgainst: 13,
    points: 4,
  },
  {
    id: "team-arch",
    name: "Architecture Aces",
    shortName: "ARCH",
    logoUrl: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=120",
    captainName: "Elena Rostova",
    department: "Architecture & Design",
    played: 6,
    won: 0,
    drawn: 0,
    lost: 6,
    goalsFor: 2,
    goalsAgainst: 15,
    points: 0,
  },
];

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: "tourn-1",
    name: "Inter-Department Football Champions Trophy 2026",
    slug: "inter-dept-football-2026",
    sport: "Football",
    season: "Spring 2026",
    status: "Ongoing",
    startDate: "2026-03-01",
    endDate: "2026-03-30",
    bannerUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800",
    totalTeams: 6,
    prizePool: "$1,500",
    description: "The premier university inter-departmental football tournament featuring 6 top department squads competing for campus championship glory.",
    teams: MOCK_TEAMS,
  },
  {
    id: "tourn-2",
    name: "Campus T20 Cricket Super League",
    slug: "campus-t20-cricket-2026",
    sport: "Cricket",
    season: "Spring 2026",
    status: "Upcoming",
    startDate: "2026-04-10",
    endDate: "2026-04-28",
    bannerUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800",
    totalTeams: 8,
    prizePool: "$2,000",
    description: "High-octane T20 cricket tournament with 8 university teams fighting for the trophy.",
    teams: MOCK_TEAMS.slice(0, 4),
  },
  {
    id: "tourn-3",
    name: "University Basketball Premier Cup",
    slug: "university-basketball-2026",
    sport: "Basketball",
    season: "Winter 2026",
    status: "Completed",
    startDate: "2026-01-15",
    endDate: "2026-02-10",
    bannerUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800",
    totalTeams: 6,
    prizePool: "$1,000",
    description: "Winter 2026 inter-department basketball cup champion CSE Strikers won in overtime thriller.",
    teams: MOCK_TEAMS,
  },
];

export const tournamentService = {
  getTournaments: async (): Promise<Tournament[]> => MOCK_TOURNAMENTS,
  getTournamentById: async (id: string): Promise<Tournament | undefined> =>
    MOCK_TOURNAMENTS.find((t) => t.id === id || t.slug === id),
};
